- app/src/controllers/document.ts
- app/src/routes/v1/document.ts
- app/src/services/document.ts
- frontend/src/assets/main.scss
- frontend/src/components/file/DocumentCard.vue
- frontend/src/components/file/FileUpload.vue
- frontend/src/components/layout/Spinner.vue
- frontend/src/lib/primevue/index.ts
- frontend/src/services/comsService.ts
- frontend/src/services/documentService.ts
- frontend/src/views/SubmissionView.vue
Implements document download and delete functionality.
Cleans up the Files tab a bit - made things a bit larger, removed the border surrounding the whole thing, added hover effects
> Document download and delete

- app/package.json
- app/src/services/chefs.ts
- frontend/src/assets/main.scss
- frontend/src/components/submission/SubmissionForm.vue
- frontend/src/views/SubmissionsView.vue
Ticket: https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3512
- Freeze the first column in the list view screen.
- When pulling the Units field from SHAS into our list view, review all 3 fields and choose the one with the largest number.
- Rename "Intake status" to "Intake state"
> UX: freeze first column in submissions list; parse submission 'number of Units' data

- app/src/db/prisma/schema.prisma
- frontend/src/components/layout/Navbar.vue
- frontend/src/views/HomeView.vue
- frontend/src/views/SubmissionView.vue
- frontend/tests/unit/components/layout/Navbar.spec.ts
Remove placeholder Vue links
Directly display initiatives selection on the homepage, with greyed out button when not logged in.
Added back button to individual submissions to go back to submissions list page
Files changed:
Navbar.vue
HomeView.vue
SubmissionVue.vue
> feat: update home page with initiative links, add back button to individual submission page

- app/src/components/constants.ts
- app/src/db/migrations/20231212000000_init.ts
- app/src/db/models/submission.ts
- app/src/db/prisma/schema.prisma
- app/src/services/chefs.ts
- app/src/types/ChefsSubmissionForm.ts
- app/src/types/ChefsSubmissionFormExport.ts
- frontend/src/components/form/Dropdown.vue
- frontend/src/components/submission/SubmissionForm.vue
- frontend/src/utils/constants.ts
- frontend/src/utils/enums.ts
Updated intake state and activity status values to title case from uppercase
Added new activity status "New"
Set default activity state to "New" on edit on frontend
Added new submission types to data model and types
Make frontend changes to allow editing new submission types
Added validation to frontend for submission types
Added new value "bcOnlineCompleted" to data model
Added checkbox for BC Online Completed to frontend
Breaking change (fix or feature that would cause existing functionality to change)
> feat: Add submittions types to data model, types, and frontend, update intake state and activity status

- app/src/components/utils.ts
- app/src/controllers/index.ts
- app/src/controllers/note.ts
- app/src/db/migrations/20231212000000_init.ts
- app/src/db/models/index.ts
- app/src/db/models/note.ts
- app/src/db/prisma/schema.prisma
- app/src/routes/v1/index.ts
- app/src/routes/v1/note.ts
- app/src/services/index.ts
- app/src/services/note.ts
- app/src/types/Note.ts
- app/src/types/index.ts
- frontend/src/components/note/NoteCard.vue
- frontend/src/components/note/NoteModal.vue
- frontend/src/components/permit/PermitCard.vue
- frontend/src/components/submission/SubmissionForm.vue
- frontend/src/services/index.ts
- frontend/src/services/noteService.ts
- frontend/src/services/userService.ts
- frontend/src/types/Note.ts
- frontend/src/types/index.ts
- frontend/src/utils/constants.ts
- frontend/src/utils/enums.ts
- frontend/src/views/SubmissionView.vue
Capability to add log notes and information that records services and informations for a submission.
Backend schema, type, and API changes required for adding a new DB table.
Frontend UI, component, type, and queries related to new DB table.
Breaking change (fix or feature that would cause existing functionality to change)
> feat: adding functionality for notes to be added in a log

- .github/environments/values.prod.yaml
Add default COMS bucket ID for production
> Add default COMS bucket ID for production

- app/src/controllers/submission.ts
- app/src/services/submission.ts
- app/src/types/ChefsSubmissionExport.ts
Adds the missing location PID field to the CHEFS Submission data load
> Add missing location PID field to data load

- app/src/controllers/submission.ts
Update a regex to cover edge cases when parsing for the largest number range 
> Fix regex parsing housing unit numbers

- app/src/controllers/roadmap.ts
- app/src/services/coms.ts
- app/src/services/index.ts
- app/src/types/Email.ts
- app/src/types/EmailAttachment.ts
- app/src/types/index.ts
- app/src/validators/roadmap.ts
- app/tests/unit/controllers/roadmap.spec.ts
- frontend/src/components/file/DocumentCard.vue
- frontend/src/components/file/FileSelectModal.vue
- frontend/src/components/roadmap/Roadmap.vue
- frontend/src/services/roadmapService.ts
- frontend/src/types/Email.ts
- frontend/src/types/index.ts
- frontend/src/views/SubmissionView.vue
Allows for any documents that have been added to the submission to be selected in a modal and attached to the email.
baed69f Only send document ID for attachments. Back end controller unit tests.
1dba864 View and modal correctly tracking selected files
1cb56e3 Allow COMS objects to be attached to emails
[SHOWCASE-3596](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3596)
> Allow COMS objects to be attached to emails

- .github/CODEOWNERS
- frontend/src/components/roadmap/Roadmap.vue
- frontend/src/utils/templates.ts
- frontend/tests/unit/utils/templates.spec.ts
This adds templating to the roadmap email. 
The roadmap email body is prepopulated with the fields as specified in the wireframe ([SHOWCASE-3440](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3440)):
* Contact name
* Location address
* Permit(s) required
* Permit(s) that *may* be required
* Permit(s) already applied
* Permit(s) completed
* Navigator name
Sections without permits are omitted entirely; e.g. if no permits are required, "You need to apply for the following permits" won't appear in the email body.
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3423
> Roadmap email body templating

- app/src/controllers/roadmap.ts
- app/src/services/coms.ts
- Checking for array length as well as truthiness.
- Only replay auth header, not the entire thing
> Resolve issue sending emails with attachments

- .github/environments/values.dev.yaml
- .github/environments/values.test.yaml
- README.md
- SECURITY.md
- app/package.json
- charts/pcns/Chart.yaml
- charts/pcns/README.md
- frontend/package.json
> Update team name/email references

- frontend/src/components/submission/SubmissionList.vue
Bring forward feature now handled in another feature. Removing extraneous UI display of Bring forward date column.
> Remove extra bring forward column in list view

- frontend/src/components/note/NoteModal.vue
- frontend/src/components/roadmap/Roadmap.vue
- frontend/src/services/roadmapService.ts
- frontend/src/utils/utils.ts
- frontend/tests/unit/service/roadmapService.spec.ts
Enable roadmap email fields to handle space, comma, and semi-colon as delimiters
Ticket: [PADS-2](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-2)
> Additional handling for email delimiters in roadmap feature

- .github/CODEOWNERS
- app/src/controllers/submission.ts
- app/src/db/models/permit.ts
- app/src/routes/v1/submission.ts
- app/src/services/activity.ts
- app/src/services/permit.ts
- app/src/services/submission.ts
- app/tests/unit/controllers/submission.spec.ts
- frontend/src/components/form/Checkbox.vue
- frontend/src/components/form/EditableDropdown.vue
- frontend/src/components/form/InputNumber.vue
- frontend/src/components/form/Password.vue
- frontend/src/components/form/TextArea.vue
- frontend/src/components/form/internal/DropdownInternal.vue
- frontend/src/components/form/internal/InputMaskInternal.vue
- frontend/src/components/form/internal/InputTextInternal.vue
- frontend/src/components/intake/ShasIntakeForm.vue
- frontend/src/components/submission/SubmissionStatistics.vue
- frontend/src/services/submissionService.ts
Improves the current SHAS intake form to allow the saving and updating of draft versions of the form.
> Allow saving and updating of intake drafts

- frontend/src/components/file/FileUpload.vue
Allow multiple files to be selected/dropped at once
> Allow multiple files to be selected for upload at once

- app/src/components/constants.ts
- app/src/controllers/enquiry.ts
- app/src/controllers/index.ts
- app/src/db/migrations/20240516000000_005-shas-enquiry.ts
- app/src/db/models/enquiry.ts
- app/src/db/models/index.ts
- app/src/db/models/submission.ts
- app/src/db/prisma/schema.prisma
- app/src/routes/v1/enquiry.ts
- app/src/routes/v1/index.ts
- app/src/services/enquiry.ts
- app/src/services/index.ts
- app/src/types/Enquiry.ts
- app/src/types/Submission.ts
- app/src/types/index.ts
- frontend/src/components/intake/ShasEnquiryForm.vue
- frontend/src/components/intake/ShasIntakeForm.vue
- frontend/src/router/index.ts
- frontend/src/services/enquiryService.ts
- frontend/src/services/index.ts
- frontend/src/utils/utils.ts
- frontend/src/views/EnquiryView.vue
- frontend/src/views/ShasEnquiryView.vue
- frontend/src/views/ShasIntakeView.vue
Implements the form functionality for the new SHAS enquiry form. Allows full submission and draft saving. If enquiry is marked as related a new note will be created in the related submission. If enquiry is marked as wanting to apply, a new submission will automatically be created and added as related to the enquiry.
> SHAS Enquiry form

- app/src/controllers/document.ts
- app/src/db/models/document.ts
- app/src/services/document.ts
- app/src/types/Document.ts
- app/tests/unit/controllers/document.spec.ts
- frontend/src/assets/variables.scss
- frontend/src/components/file/DeleteDocument.vue
- frontend/src/components/file/DocumentCard.vue
- frontend/src/components/file/FileUpload.vue
- frontend/src/types/Document.ts
- frontend/src/views/SubmissionView.vue
PADS-24: Files tab - improve view and findability
Describe your changes in detail:
Added list view to the files tab 
New upload button added
Added button to switch between grid and list views
Added search and sort functionality for files in both views
Changed list documents api to fetch created_by information
Changed created documents api to save information of user to the db
Modularized delete document view and functions
> Files tab - improve view and findability

- frontend/src/views/StartView.vue
- frontend/src/views/SubmissionView.vue
Resolve an initialization order issue in the StartView.
04d376c Resolve initialization order issue
> Resolve initialization order issue

- frontend/src/components/form/Checkbox.vue
- frontend/src/components/form/EditableDropdown.vue
- frontend/src/components/form/InputMask.vue
- frontend/src/components/form/InputNumber.vue
- frontend/src/components/form/InputText.vue
- frontend/src/components/form/Password.vue
- frontend/src/components/form/TextArea.vue
- frontend/src/components/submission/SubmissionStatistics.vue
PADS-178: Bug noticed by navs where backspacing caused the whitespace to be removed automatically
Removed internal form components from the cherrypick
(cherry picked from commit d788649f29f3c253315ea794c44818f427669731)
Describe your changes in detail
Slipstream fix to remove .trim from form components
58da8381f3743f2e0a578d91191a69ffe6684982 - Slipstream fix to remove .trim from form components
Slipstream fix to remove .trim from form components
> Remove .trim from form components

- frontend/src/components/housing/intake/ShasIntakeForm.vue
Hides the intake error banner after a user makes a form change.
https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-163
Required field warnings are still displayed on Intake form after all are completed
> Dismiss intake error banner

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/housing/submission/SubmissionForm.vue
- frontend/src/components/housing/submission/SubmissionListNavigator.vue
- frontend/src/components/housing/submission/SubmissionsNavigator.vue
- frontend/src/types/Submission.ts
- frontend/src/views/housing/submission/SubmissionView.vue
Revamped SubmissionListNavigator based on criteria in the comment (11:59am) in [PADS-189](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-189). 
Feature, added visibility and functionality to the tabes fields to greater help Navigators utilize the Submissions List.
> Revamped SubmissionListNavigator

- app/src/controllers/activity.ts
- app/src/controllers/index.ts
- app/src/routes/v1/activity.ts
- app/src/routes/v1/index.ts
- app/src/utils/constants/application.ts
- app/tests/unit/controllers/activity.spec.ts
- frontend/src/components/housing/enquiry/EnquiryIntakeForm.vue
- frontend/src/services/activityService.ts
- frontend/src/services/index.ts
- frontend/src/utils/constants/application.ts
- frontend/src/views/DeveloperView.vue
Made it so that a warning toast pops out when the confirmation id (activityId) entered by the proponent doesn't return a submissions search result.
Proponents will now be visually told that they are entering an invalid id but not stopped from doing so.
[PADS-181](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-181)
> Validate confirmation Id (activityId) for Enquiries

- frontend/src/components/form/InputNumber.vue
- frontend/src/components/form/InputText.vue
- frontend/src/components/form/internal/InputTextInternal.vue
Help text on form components like InputText now always displays
so that the user can see the help text without needing to clicking into field, saving confusion
[PADS-245](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-245)
> Help text for Form components always shows (like Parcel Ids on submission intake)

- frontend/src/components/housing/submission/SubmissionBringForwardCalendar.vue
- frontend/src/components/housing/submission/SubmissionsNavigator.vue
- frontend/src/types/Submission.ts
- frontend/tests/unit/components/submission/SubmissionBringForwardCalendar.spec.ts
BF notifications accordion and show mine only list in BF Calendar now both show notes authored and assigned to
Capture the submissions/projects that a user is assigned to and cross reference that with BF Notes connected to said assigned projects.
So that when a navigator assigns someone else to the project they will also get the bring forward notification
[PADS-244](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-244)
> BF Notes now being reassigned

- .github/environments/values.dev.yaml
- frontend/src/components/file/AdvancedFileUpload.vue
- frontend/src/components/file/DeleteDocument.vue
- frontend/src/components/file/DocumentCardLite.vue
- frontend/src/components/housing/submission/SubmissionIntakeForm.vue
- frontend/src/services/documentService.ts
- frontend/src/utils/constants/application.ts
- frontend/tests/unit/service/documentService.spec.ts
Proponent can select to attach a file much the same way Navigators do on the Files tab
Upon submission, the file will be stored in the Files tab for the submission.
https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-141
> Proponent File Upload

- .github/environments/values.dev.yaml
- app/config/custom-environment-variables.json
- app/src/controllers/roadmap.ts
- app/src/interfaces/IExpress.ts
- app/src/middleware/authentication.ts
- app/src/middleware/requireSomeGroup.ts
- app/src/services/coms.ts
- app/src/services/yars.ts
- app/src/types/CurrentContext.ts
- app/tests/unit/controllers/roadmap.spec.ts
- charts/pcns/Chart.yaml
- charts/pcns/README.md
- charts/pcns/templates/deploymentconfig.yaml
- charts/pcns/templates/secret.yaml
- charts/pcns/values.yaml
Using the updated COMS API, this implementation allows the system to impersonate the current user and grant themselves access to the PCNS bucket based on their given group in the RBAC.
https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-239
> Automatically grant COMS permissions for new users

- app/src/db/migrations/20240828000000_008-user-id-constraint.ts
- app/src/db/prisma/schema.prisma
Create a migration to remove duplicate users in the Users table.
Add a constraint at the database level for Users table to prevent duplicate users to be added to the table.
[PADS-277](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-277)
> Remove duplicated users in database, prevent reoccurrence 

- app/src/controllers/permit.ts
- app/src/db/migrations/20240718000000_007-rbac.ts
- app/src/routes/v1/permit.ts
- app/src/services/permit.ts
- app/src/validators/permit.ts
- app/tests/unit/controllers/permit.spec.ts
- frontend/src/components/housing/submission/SubmissionListNavigator.vue
- frontend/src/components/housing/submission/SubmissionStatistics.vue
- frontend/src/components/housing/submission/SubmissionsNavigator.vue
- frontend/src/services/permitService.ts
- frontend/src/types/Statistics.ts
- frontend/src/types/Submission.ts
- frontend/tests/unit/service/permitService.spec.ts
[PADS-252](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-252)
Multi-permits needed (Multi-Authorization Project) stats obtained (Projects with more than one permit with needed set to Yes)
rbac migration updated with statistics db function changes
list permits endpoint updated to make activityId optional
stats tab updated, submission data-table updated to show multi-auth column
multiPermitsNeeded property added to submission frontend type (this makes it easier for datatable to grab the value, also makes it sortable)
> Add multi-permits needed statistic

- app/src/controllers/enquiry.ts
- app/src/controllers/submission.ts
- app/src/routes/v1/submission.ts
- app/src/services/submission.ts
- frontend/src/components/housing/enquiry/EnquiryIntakeForm.vue
- frontend/src/components/housing/submission/SubmissionsProponent.vue
- frontend/src/services/enquiryService.ts
- frontend/src/services/submissionService.ts
- frontend/tests/unit/components/shasIntake/EnquiryIntakeForm.spec.ts
- frontend/tests/unit/service/enquiryService.spec.ts
- frontend/tests/unit/service/submissionService.spec.ts
[PADS-272](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-272)
self scope is now being checked on calling getActivityIds endpoint
hasAuthorization added to the endpoint
getActivityIds function removed from service layer and instead now using getSubmissions and filtering the data in the controller
InputText replaced with EditableDropdown in enquiry intake form for related submissions
> Proponent related submissions dropdown

- frontend/src/components/housing/enquiry/EnquiryIntakeForm.vue
- frontend/src/components/housing/submission/IntakeAssistanceConfirmation.vue
- frontend/src/components/housing/submission/SubmissionIntakeForm.vue
- frontend/src/utils/templates.ts
[PADS-282](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-282)
Email template updated
Enquiry Description added to the email template
html query parameter added to email endpoint
email service layer updated to pass html data to chefs depending on the content
> Proponent Confirm Email Updates

- frontend/src/components/form/AutoComplete.vue
- frontend/src/components/form/Calendar.vue
- frontend/src/components/form/Checkbox.vue
- frontend/src/components/form/EditableDropdown.vue
- frontend/src/components/form/InputNumber.vue
- frontend/src/components/form/Password.vue
- frontend/src/components/form/RadioList.vue
- frontend/src/components/form/StepperNavigation.vue
- frontend/src/components/form/TextArea.vue
- frontend/src/components/form/internal/DropdownInternal.vue
- frontend/src/components/form/internal/InputMaskInternal.vue
- frontend/src/components/form/internal/InputTextInternal.vue
- frontend/src/components/layout/Navbar.vue
Adds `aria-labelledby` to form components
Resolves keyboard navigation highlighting issue
> Accessibility updates

- frontend/src/App.vue
- frontend/src/router/index.ts
- frontend/src/utils/enums/application.ts
- frontend/src/views/oidc/OidcCallbackView.vue
- frontend/src/views/user/UserManagementView.vue
Updates the router to ensure consistent behaviour with refreshing in both local development and deployments.
> Add beforeEnter guards to router

- app/src/db/migrations/20240919000000_010-statistics-update.ts
- frontend/src/components/housing/submission/SubmissionStatistics.vue
Update statistics function to not include submissions and enquiries in Draft status
Updates statistics table to clarify total count
> Update statistics to not include drafts

- frontend/src/components/housing/submission/SubmissionIntakeForm.vue
It was causing a duplicate entry to be created. Also unnecessary with the auto saving feature in place.
> Remove draft saving on stepper navigation

- frontend/src/components/housing/enquiry/EnquiryIntakeForm.vue
- frontend/src/components/housing/submission/SubmissionIntakeForm.vue
- frontend/tests/unit/components/shasIntake/EnquiryIntakeForm.spec.ts
[PADS-242](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-242)
FormNavigationGuard added to Submission and Enquiry intake
> Use FormNavigationGuard in intake forms

- app/src/controllers/enquiry.ts
- app/src/controllers/submission.ts
- app/src/routes/v1/enquiry.ts
- app/src/routes/v1/submission.ts
- app/src/validators/enquiry.ts
- app/tests/unit/controllers/submission.spec.ts
- frontend/src/components/housing/enquiry/EnquiryIntakeForm.vue
- frontend/src/components/housing/submission/SubmissionIntakeForm.vue
- frontend/src/services/enquiryService.ts
- frontend/src/services/submissionService.ts
- frontend/src/views/housing/enquiry/EnquiryIntakeView.vue
- frontend/src/views/housing/project/ProjectView.vue
- frontend/src/views/housing/submission/SubmissionIntakeView.vue
- frontend/tests/unit/service/enquiryService.spec.ts
Submission & Enquiry draft endpoints updated to be
- `PUT /draft`
- to keep a draft in `DRAFT` status
- `PUT /draft/submit`
- finalize a draft and put it into `SUBMITTED` status
Param no longer required. Controller will read directly from the body and create or update data as required. 
Route query is updated on save to allow for correct browser refresh.
https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-298
Bug fix (non-breaking change which fixes an issue) 
> Changes to Submission/Enquiry draft saving endpoints

- app/src/controllers/ats.ts
- app/src/routes/v1/ats.ts
- app/src/services/ats.ts
- app/src/types/ATSClientResource.ts
- app/src/types/index.ts
- app/src/validators/ats.ts
- app/src/validators/index.ts
- app/tests/unit/controllers/ats.spec.ts
- frontend/src/components/housing/submission/SubmissionForm.vue
- frontend/src/components/user/ATSUserCreateModal.vue
- frontend/src/components/user/ATSUserDetailsModal.vue
- frontend/src/components/user/ATSUserLinkModal.vue
- frontend/src/services/atsService.ts
- frontend/src/types/ATSClientResource.ts
- frontend/src/types/ATSUser.ts
- frontend/src/types/index.ts
[PADS-231](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-231) - ATS Client Push API
[PADS-317](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-317) - ATS Client Push UI
ATS client push UI: 
New ATSUserCreateModal
New frontend type for ATSClientResource
SubmissionForm, ATSUserLinkModal, ATSUserDetailModal, atsService updated
ATS client push API: 
New POST API for creating clients in ATS
New backend type ATSClientResource, ATSUserSearchParameters
atsController, route, services, validator updated
Backend unit test added
> ATS Client Push

- app/src/controllers/accessRequest.ts
- app/src/controllers/yars.ts
- app/src/db/models/access_request.ts
- app/src/db/prisma/schema.prisma
- app/src/routes/v1/yars.ts
- app/src/services/accessRequest.ts
- app/src/types/index.ts
- frontend/src/components/user/UserCreateModal.vue
- frontend/src/components/user/UserManageModal.vue
- frontend/src/components/user/UserProcessModal.vue
- frontend/src/components/user/UserTable.vue
- frontend/src/services/yarsService.ts
- frontend/src/views/user/UserManagementView.vue
1. Cleaned up functionality for User Management View/ Table.
2. Changed flow for Admin users so that they have one table for managing users and one for managing user access/revocation requests. See [FIGMA](https://www.figma.com/design/udtqyDmqaYte03ANaS10S2/PAT?node-id=3762-2120)
3. Added ability to revoke users
4. Cleaned up Create User Modal
These changes help with the functionality of user maangement table and solves refreshing issues, creates a cleaner flow for admins users, allows users' access to be revoked by Admins and Supervisors to request revocation, and better usability for creating users.
[PADS-257](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-237)
[PADS-309](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-309)
New feature …
> Update/Clean Up User Management & Add Revoke

- frontend/src/components/file/AdvancedFileUpload.vue
- frontend/src/components/form/internal/InputMaskInternal.vue
- frontend/src/components/housing/submission/SubmissionIntakeForm.vue
When changing steps in the submission intake form autosave is no longer triggered, onBlur for phone number doesn't trigger autosave anymore, and no more double autosave on initial save of draft.
Keeps empty drafts from cluttering the draft and submissions table.
[PADS-337](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-337)
> Fixed autosave from triggering on empty forms

- frontend/src/components/permit/PermitStatusDescriptionModal.vue
Permit Tracker - Status description modal
> Permit Tracker - Status description modal

- app/src/controllers/submission.ts
- app/src/routes/v1/submission.ts
- frontend/src/components/housing/submission/SubmissionIntakeForm.vue
Now using proper middleware when reopening a draft. Resolves 403 error being received previously.
Correctly reloading documents for drafts & submitted intakes.
Resolve issue with creating a draft via file upload.
https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-387
> Resolve draft create/reopening issues

- frontend/src/components/permit/PermitCard.vue
Made it so Add updates for permit card also greyouts like the edit button
completed projects shouldn't have new info coming in
[PR-389](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-389)
> Permit Add update button now greyed out for completed projects

- frontend/src/components/common/StatusPill.vue
- frontend/src/components/housing/projects/ProjectsList.vue
- frontend/src/components/permit/PermitModal.vue
- frontend/src/components/permit/PermitStatusDescriptionModal.vue
- frontend/src/utils/constants/housing.ts
- frontend/src/views/housing/project/ProjectView.vue
Updated submitted applications permit page with new card designs, wording consistencies, and utilizing new StatusPill component.
[PADS-359](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-359)
> Update submitted applications page

- frontend/src/components/housing/submission/SubmissionIntakeForm.vue
Empty optional permits no longer error out on submission.
Helps with flow
[PADS-390](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-390)
NOTE: Also fixed issue with confirmation email sending and removed function variables that matched the component's props.
> Optional permit entries started and not finished causes error

- frontend/src/components/housing/submission/SubmissionIntakeForm.vue
- frontend/src/views/permit/PermitStatusView.vue
Set max date to current date and fixed formatting issue.
Usability.
[PADS-383](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-383)
Deleted some commented code that snuck in on a previous branch.
> Submission Intake Form - bugs in proponent entered applied permits

- frontend/src/assets/main.scss
- frontend/src/components/housing/submission/SubmissionListNavigator.vue
- frontend/src/components/layout/AppLayout.vue
- frontend/src/components/layout/Footer.vue
- frontend/src/locales/en-CA.json
- frontend/src/views/DeveloperView.vue
- frontend/src/views/HomeView.vue
- frontend/tests/unit/components/layout/Footer.spec.ts
Aligning to new style guide
https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-372?
> Update application footer

- .github/workflows/on-pr-closed.yaml
- .github/workflows/on-pr-opened.yaml
- .github/workflows/on-push.yaml
Ubuntu latest (24.04) no longer installs `oc` by default. Have to manually add this step to the pipeline. Pegging to `4.16`. This will default to the latest patch version of 4.16.
> Ubuntu 24 no longer has `oc` by default

- frontend/src/components/housing/enquiry/EnquiryIntakeForm.vue
- frontend/src/components/housing/submission/SubmissionIntakeForm.vue
[PADS-410](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-410)
Back navigation link fix for Proponent views
> Back navigation link fix for Proponent views

- app/src/controllers/submission.ts
- app/src/validators/appliedPermit.ts
- app/tests/unit/controllers/submission.spec.ts
- app/tests/unit/validators/appliedPermits.spec.ts
- frontend/src/assets/main.scss
- frontend/src/components/form/StepperHeader.vue
- frontend/src/components/housing/enquiry/EnquiryForm.vue
- frontend/src/components/housing/enquiry/EnquiryIntakeForm.vue
- frontend/src/components/housing/enquiry/EnquiryListProponent.vue
- frontend/src/components/housing/submission/SubmissionDraftListProponent.vue
- frontend/src/components/housing/submission/SubmissionForm.vue
- frontend/src/components/housing/submission/SubmissionIntakeForm.vue
- frontend/src/components/housing/submission/SubmissionIntakeSchema.ts
- frontend/src/utils/enums/housing.ts
- frontend/src/validators/contact.ts
- frontend/tests/unit/components/shasIntake/EnquiryIntakeForm.spec.ts
- frontend/tests/unit/components/shasIntake/SubmissionIntakeForm.spec.ts
Stepper style updates
Intake validation fixes
Intake wording updates
Bug fix (?) for auto save triggering on older submitted intakes
https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-398
> Stepper style updates

- frontend/src/components/common/BackButton.vue
- frontend/src/components/common/Breadcrumb.vue
- frontend/src/components/common/StatusPill.vue
- frontend/src/components/file/DeleteDocument.vue
- frontend/src/components/file/DocumentCard.vue
- frontend/src/components/file/DocumentCardLite.vue
- frontend/src/components/housing/enquiry/EnquiryIntakeForm.vue
- frontend/src/components/housing/submission/SubmissionAssistance.vue
- frontend/src/components/housing/submission/SubmissionIntakeForm.vue
- frontend/src/components/layout/Footer.vue
- frontend/src/locales/en-CA.json
- frontend/src/utils/utils.ts
- frontend/src/views/housing/HousingView.vue
- frontend/src/views/housing/project/ProjectView.vue
- frontend/src/views/permit/PermitStatusView.vue
- frontend/tests/unit/components/file/DeleteDocument.spec.ts
- frontend/tests/unit/components/file/DocumentCard.spec.ts
- frontend/tests/unit/views/housing/HousingView.spec.ts
Ensured and added the ability to navigate the application (proponent side) with keyboard
So that we are WCAG 2.2 compliant for public facing components
[PADS-310](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-310)
New feature (non-breaking change which adds functionality) 
The tests that would cover keyboard navigation are too in depth to implement for this ticket. Should be applied to future Integration level Testing.
> Ensured and added keyboard navigation for public facing components

- app/src/services/submission.ts
- frontend/src/components/housing/submission/SubmissionIntakeForm.vue
- frontend/tests/unit/components/shasIntake/SubmissionIntakeForm.spec.ts
Resolve issue with form incorrectly setting read-only state.
https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-418
> Resolve issue with form incorrectly setting read-only state

- app/src/controllers/submission.ts
- app/src/utils/utils.ts
- app/tests/unit/controllers/submission.spec.ts
- frontend/src/views/DeveloperView.vue
CHEFS form no longer in use and has been disabled. Data exists in DB backups. Call no longer necessary.
https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-179
> Remove API call to pull CHEFS intake form data

- frontend/src/components/file/AdvancedFileUpload.vue
- frontend/src/components/form/FormAutosave.vue
- frontend/src/components/housing/submission/SubmissionIntakeForm.vue
Autosave no longer tracks activity Id within the form as it isn't a form field that needs to be tracked for autosave and validation.
This will prevent autosave from either double saving or removing validation errors.
[PADS-416](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-416)
> Prevent autosave from clearing form error messages.

- frontend/src/components/permit/NotesModal.vue
- frontend/src/components/permit/PermitCard.vue
- frontend/src/views/housing/submission/SubmissionView.vue
Made it so new updates were also updating the store and not just component local notes list.
So that when new notes were added to a new permit they'd appear on the page without refresh
[PADS-435](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-435)
> Permit notes now updating on new permits

- app/src/controllers/contact.ts
- app/src/services/contact.ts
- app/src/services/user.ts
- app/src/validators/contact.ts
- frontend/src/components/housing/enquiry/EnquiryIntakeForm.vue
- frontend/src/components/housing/submission/SubmissionIntakeForm.vue
- frontend/src/validators/contact.ts
- frontend/src/views/contact/ContactProfileView.vue
- frontend/tests/unit/components/shasIntake/EnquiryIntakeForm.spec.ts
[PADS-436](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-436)
BCeID was passing both fn and ln in given_name, now we're splitting it on space to fn and ln.
> BCeID FN LN Issue Fix
