.github/workflows/on-pr-opened.yaml, .github/workflows/on-push.yaml
Renaming is hard.
[SHOWCASE-3446](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3446)
=> Rename APP_NAME to match with new repository rename

app/src/controllers/chefs.ts, app/src/services/chefs.ts, app/src/services/user.ts, app/src/types/ChefsSubmissionFormExport.ts, app/src/types/SubmissionSearchParameters.ts, app/src/types/index.ts, frontend/src/types/ChefsSubmissionForm.ts, frontend/src/views/SubmissionsView.vue
- Updates and aligns the submissions view with the new UX/UI design
- Adds a submissions search endpoint
- Resolves a bug in the user search endpoint
=> Submissions view UX/UI alignment

.github/environments/values.test.yaml
Add COMS bucket ID to environment config for TEST github environment
=> Add COMS bucket ID to config in Helm chart

frontend/src/components/submission/SubmissionForm.vue, frontend/src/components/submission/SubmissionList.vue, frontend/src/components/submission/SubmissionStatistics.vue, frontend/src/views/SubmissionView.vue
Show submission types in list view
Fix typos in components
=> feat: minor UI update for SubmissionList, SubmissionForm, some UI fixes

frontend/src/components/submission/SubmissionForm.vue, frontend/src/components/submission/SubmissionList.vue, frontend/src/components/submission/SubmissionStatistics.vue
Change text "inquiry" to "enquiry" In SubmissionForm, SubmissionList, SubmissionStatistics 
Change "Intake status" to "intake state" in SubmissionList
=> Component UI/UX text changes

app/src/controllers/submission.ts
Parse housing units data such that "greaterthan[number]" value from CHEFS is replaced with ">[number]".
=> Additional parsing for housing unit numbers

bcgovpubcode.yml
=> Add bcgovpubcode.yml

app/src/services/email.ts, app/src/validators/roadmap.ts, frontend/src/components/roadmap/Roadmap.vue, frontend/src/utils/utils.ts
- Added Joi validation for the email bosy sent to CHES email service
- show service errors in Toast on frontend
=> Joi validation of roadmap email

app/src/controllers/note.ts, app/src/controllers/roadmap.ts, app/src/db/models/note.ts, app/src/types/Note.ts, app/src/validators/roadmap.ts, app/tests/unit/controllers/roadmap.spec.ts
Creates a new note in the submission when a roadmap email is succesfully dispatched. The note contains the email body, and appends attached file names if they exist.
2bead05 Create a new note when roadmap email is successfully dispatched
[SHOWCASE-3597](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3597)
=> Create a roadmap note on email dispatch

.github/workflows/on-pr-closed.yaml, .github/workflows/on-pr-opened.yaml
Allows feature branch pull requests to deploy to dev
=> Allow feature branch pull requests to deploy to dev

charts/pcns/templates/deploymentconfig.yaml, charts/pcns/templates/secret.yaml
fix helm variable for ches secret
=> fix helm variable for ches secret

charts/pcns/Chart.yaml, charts/pcns/README.md
Bump chart version and update docs
=> increment helm release version

app/src/controllers/note.ts, app/src/db/models/note.ts, app/src/db/models/submission.ts, app/src/db/models/user.ts, app/src/routes/v1/note.ts, app/src/services/note.ts, app/src/services/submission.ts, app/src/services/user.ts, app/src/types/BringForward.ts, app/src/types/index.ts, app/tests/unit/controllers/note.spec.ts, frontend/package-lock.json, frontend/package.json, frontend/src/components/form/Calendar.vue, frontend/src/components/submission/SubmissionBringForwardCalendar.vue, frontend/src/components/submission/SubmissionForm.vue, frontend/src/components/submission/SubmissionStatistics.vue, frontend/src/lib/primevue/index.ts, frontend/src/services/noteService.ts, frontend/src/types/BringForward.ts, frontend/src/types/index.ts, frontend/src/utils/constants.ts, frontend/src/views/SubmissionView.vue, frontend/src/views/SubmissionsView.vue, frontend/tests/unit/service/noteService.spec.ts
Adds a new bring forward tab to the submissions view.
- Contains a sortable table of all unresolved bring forward notes
- Can be filtered to the logged in user
Adds an accordion to the submissions list
- Shows unresolved bring forward notifications for the logged in user
- colour coded by urgency
7d68353 Add colour coded bring forward notifications to submission list view
ede9e30 Implement Bring Forward tab & table
[https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3558](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3558)
[https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3559](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3559)
=> Bring forward tab and submission bring forward notifications

frontend/src/components/note/NoteCard.vue, frontend/src/components/permit/PermitCard.vue, frontend/src/components/roadmap/Roadmap.vue, frontend/src/services/roadmapService.ts, frontend/src/utils/utils.ts, frontend/src/views/SubmissionView.vue
51fc346 Consistency in permit and note card titles
17405a8 Semicolon delimiter for emails
=> Minor adjustments from demo feedback

frontend/src/views/SubmissionView.vue
Wait for the data load to be completed before passing props to the submission form - otherwise stale data is sent.
=> Wait for data load before rendering form SubmissionForm

frontend/src/lib/primevue/index.ts, frontend/src/router/index.ts, frontend/src/utils/constants.ts, frontend/src/views/EnquiryView.vue, frontend/src/views/HomeView.vue, frontend/src/views/IntakeFormView.vue, frontend/src/views/StartView.vue
Added choose pcns intake form or enquiry, disclaimer, cleanup, removed authentication restriction for Housing button
New feature (non-breaking change which adds functionality) 
Ticket: [PADS-67](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-67)
=> Choose PCNS Intake Form or Enquiry, Disclaimer pages

.github/workflows/on-pr-closed.yaml, .github/workflows/on-pr-opened.yaml
Add 'release/**' to PR pipelines
=> Add 'release/**' to PR pipelines

app/src/components/constants.ts, app/src/controllers/submission.ts, app/src/db/migrations/20240402000000_002-submission-updates.ts, app/src/routes/v1/enquiry.ts, app/src/routes/v1/submission.ts, app/src/types/Middleware.ts, app/src/types/index.ts, app/src/validators/basic.ts, app/src/validators/enquiry.ts, app/src/validators/index.ts, app/src/validators/submission.ts, app/tests/unit/validators/basic.spec.ts, frontend/src/components/form/TextArea.vue, frontend/src/components/intake/ShasEnquiryForm.vue, frontend/tests/unit/components/shasIntake/ShasEnquiryForm.spec.ts
Add front and backend validation to enquiry form functionality.
https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-139
https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-140
=> Enquiry form validation

app/src/validators/permit.ts, app/tests/unit/controllers/permit.spec.ts, frontend/src/components/form/Calendar.vue, frontend/src/components/permit/PermitCard.vue, frontend/src/components/permit/PermitModal.vue, frontend/src/types/PermitForm.ts, frontend/src/utils/formatters.ts
PADS-159: Added last verified date to Permit tab
Auth status and Permit ID renamed
Set max date for Submitted date & Adjudication date
1b2e87a52a56b49e59dab41f70e203c8b283ea79 - Permit tab - added last verified date
=> Permit tab - Added Last Verified Date

frontend/src/components/permit/PermitCard.vue, frontend/src/components/permit/PermitModal.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-188
Renamed "Last Verified Date" to "Status verified date" on card/add/edit. 
Moved "Needed" field location to before the "Authorization status" field on  add / edit permit view.
=> Permit tab minor UI changes

frontend/src/components/layout/Navbar.vue, frontend/src/router/index.ts, frontend/src/utils/constants/application.ts, frontend/src/utils/constants/housing.ts, frontend/src/utils/enums/application.ts
Help tab on menu
Provide a quick way to contact a Navigator until such time as we have the assistance flow
[PADS-184](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-184)
=> New Help tab

frontend/src/components/roadmap/Roadmap.vue, frontend/src/services/roadmapService.ts, frontend/src/utils/utils.ts
[PADS-200](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-200)
RoadMap:
To and BCC emails are required now.
BCC will be sent to the default mailbox even if the default mail removed.
=> Improved roadmap validation

app/src/controllers/note.ts, app/src/services/enquiry.ts, app/src/types/EnquirySearchParameters.ts, app/src/types/index.ts, app/tests/unit/controllers/note.spec.ts, frontend/src/components/housing/submission/SubmissionBringForwardCalendar.vue, frontend/src/components/housing/submission/SubmissionsNavigator.vue, frontend/src/components/note/NoteCard.vue, frontend/src/components/note/NoteModal.vue, frontend/src/types/BringForward.ts, frontend/src/views/housing/enquiry/EnquiryView.vue, frontend/src/views/housing/submission/SubmissionView.vue
Notes added to Enquiry
[PADS-192](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-192)
=> Notes added to Enquiry

app/src/controllers/enquiry.ts, app/src/controllers/submission.ts, app/src/db/migrations/20240621180350_005_soft-delete-activity.ts, app/src/db/models/activity.ts, app/src/db/prisma/schema.prisma, app/src/routes/v1/enquiry.ts, app/src/routes/v1/submission.ts, app/src/services/enquiry.ts, app/src/services/note.ts, app/src/services/submission.ts, app/src/types/Activity.ts, app/src/types/SubmissionSearchParameters.ts, app/src/validators/enquiry.ts, app/src/validators/submission.ts, app/tests/unit/controllers/submission.spec.ts, frontend/src/components/housing/enquiry/EnquiryListNavigator.vue, frontend/src/components/housing/submission/SubmissionListNavigator.vue, frontend/src/components/housing/submission/SubmissionListProponent.vue, frontend/src/components/housing/submission/SubmissionStatistics.vue, frontend/src/components/housing/submission/SubmissionsNavigator.vue, frontend/src/services/enquiryService.ts, frontend/src/services/submissionService.ts, frontend/src/types/Activity.ts
[PADS-183](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-183)
Added is_deleted column to activity, excluded deleted records from statistics
Delete feature added to navigator view for both enquiries and submissions
Updated notes and BF to ignore the notes linked deleted activities
=> Delete Submissions Feature

app/src/validators/housing.ts, app/src/validators/submission.ts, frontend/src/components/form/TextArea.vue, frontend/src/components/housing/submission/SubmissionForm.vue
Removed 255 character limits on AST Notes and added a 4000 character limit to the TextArea Component.
Navigators need the ability to take many notes.
[PADS-210](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-210)
=> Remove 255 Character Limits on TextArea components

frontend/src/components/layout/Navbar.vue, frontend/src/services/permissionService.ts, frontend/src/views/housing/HousingView.vue
[PADS-206](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-206)
Hide status tracker and show housing dropdown for navs
=> Hide Status Tracker

app/src/db/migrations/20240621180350_005_soft-delete-activity.ts, app/src/db/migrations/20240705000000_006_statistics-function-update.ts, app/src/db/migrations/20240705184109_006_statistics-function-update.ts, frontend/src/components/housing/submission/SubmissionStatistics.vue, frontend/src/types/Statistics.ts
Enquiry and financially supported stats added
=> Statistics Function Updates

app/src/validators/submission.ts, frontend/src/components/housing/submission/SubmissionForm.vue, frontend/src/types/Submission.ts
[PADS-229](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-229)
Added additional information about location field added to nav info tab
=> Add missing Location Additional Information

app/src/db/README.md
DB restore instructions added to app/src/db/README.md 
Documentation (non-breaking change with enhancements to documentation)
=> Update db README

frontend/src/components/housing/submission/SubmissionIntakeForm.vue
[PADS-221](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-221)
Clear location coordinates on radio button on-change instead of on click
=> Clear Location Coordinates on Radio Button Change

frontend/src/components/housing/enquiry/EnquiryIntakeForm.vue, frontend/src/components/housing/submission/SubmissionIntakeForm.vue, frontend/src/composables/formAutoSave.ts
Made it so that intake forms for proponents autosave on 10 seconds of inactivity.
This helps prevents data loss when proponents are entering information to forms
=> Implemented autosave functionality for intake forms that utilize a save draft feature

app/src/controllers/submission.ts, frontend/src/components/form/RadioList.vue, frontend/src/components/housing/enquiry/EnquiryIntakeForm.vue, frontend/src/components/housing/maps/Map.vue, frontend/src/components/housing/submission/SubmissionAssistance.vue, frontend/src/components/housing/submission/SubmissionIntakeForm.vue, frontend/src/components/housing/submission/SubmissionIntakeSchema.ts, frontend/src/views/housing/enquiry/EnquiryIntakeView.vue, frontend/src/views/housing/submission/SubmissionIntakeView.vue, frontend/tests/unit/components/shasIntake/EnquiryIntakeForm.spec.ts, frontend/tests/unit/components/shasIntake/SubmissionIntakeForm.spec.ts
A variety of bug fixes for the enquiry intake and submission intake forms:
* Removing Submission Assistance where unnecessary
* Removing ability to edit certain form parts when it is read-only
* Remove unnecessary confirmation modals when navigating with the back button
* Adjusting form validation so it does not trigger prematurely
[PADS-255](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-255)
[PADS-257](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-257)
=> Fixing several bugs in enquiry intake and submission intake forms

app/src/controllers/accessRequest.ts, app/src/db/models/access_request.ts, app/src/routes/v1/accessRequest.ts, app/src/services/accessRequest.ts, app/src/types/AccessRequest.ts, frontend/src/components/user/UserActionModal.vue, frontend/src/components/user/UserTable.vue, frontend/src/services/accessRequestService.ts, frontend/src/types/User.ts, frontend/src/views/user/UserManagementView.vue
[PADS-223](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-223)
Admin:
Create & revoke user
Approve & deny access requests
=> User Management Admin Backend Implementation

app/src/controllers/submission.ts, app/src/routes/v1/submission.ts, app/src/services/submission.ts, app/src/types/SubmissionSearchParameters.ts, app/src/utils/constants/housing.ts, app/src/validators/submission.ts, frontend/src/assets/main.scss, frontend/src/assets/variables.scss, frontend/src/components/common/Breadcrumb.vue, frontend/src/components/housing/enquiry/EnquiryIntakeForm.vue, frontend/src/components/housing/projects/ProjectPermitModal.vue, frontend/src/components/housing/projects/ProjectsList.vue, frontend/src/components/layout/Navbar.vue, frontend/src/components/permit/PermitModal.vue, frontend/src/router/index.ts, frontend/src/utils/enums/application.ts, frontend/src/utils/utils.ts, frontend/src/views/housing/HousingView.vue, frontend/src/views/housing/ProjectsView.vue, frontend/src/views/housing/enquiry/EnquiryIntakeView.vue, frontend/src/views/housing/project/ProjectListView.vue, frontend/src/views/housing/project/ProjectView.vue, frontend/src/views/housing/submission/SubmissionView.vue
Implement ability for proponents to see their list of submissions and the individual submission progress 
=> Implement proponent project list and project views

app/src/controllers/enquiry.ts, app/src/db/migrations/20240819000000_007-assistance-update.ts, app/src/db/migrations/20240819000000_008-assistance-update.ts, app/src/utils/constants/housing.ts, app/src/utils/enums/housing.ts, app/src/validators/basic.ts, frontend/src/components/housing/submission/IntakeAssistanceConfirmation.vue, frontend/src/components/housing/submission/SubmissionAssistance.vue, frontend/src/components/housing/submission/SubmissionIntakeForm.vue, frontend/src/utils/constants/housing.ts, frontend/src/utils/enums/housing.ts
When using the assistance flow tab, it will save any fields filled in for submission as a draft.
It will then create an enquiry with the filled in applicant information with an "Assistance" status.
The Enquiry and draft Submission will be connected through their activity IDs.
[PADS-253](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-253)
=> Update assistance flow to also save current submission as draft

app/src/controllers/enquiry.ts, app/src/db/models/enquiry.ts, app/src/routes/v1/enquiry.ts, app/src/validators/enquiry.ts, frontend/src/components/housing/enquiry/EnquiryCard.vue, frontend/src/services/enquiryService.ts, frontend/src/store/submissionStore.ts, frontend/src/views/housing/enquiry/EnquiryView.vue, frontend/src/views/housing/submission/SubmissionView.vue
[PADS-208](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-208)
Related Enquiries Tab added to Submission Navigator view.
Enquiries are no longer added to db as notes or shown as notes in the frontend
Started filling stamps data in Enquiry table (enquiry model updated)
Related enquiries added to Submission store
New endpoint for listing related enquiries
New Enquiry card component similar to Note card
=> Related Enquiries Tab

app/src/controllers/submission.ts, app/src/routes/v1/submission.ts, app/src/services/submission.ts, frontend/src/components/housing/enquiry/EnquiryForm.vue, frontend/src/services/submissionService.ts, frontend/src/views/housing/enquiry/EnquiryView.vue
[PADS-209](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-209)
New endpoint added to obtain all the activity ids from submission table
Related submission can be updated from the enquiry detail
is_related column is updated to Yes/No depending on the related submission field
Related submission now uses editable dropdown to show search suggestions
=> Change Related Enquiry

frontend/src/components/housing/submission/SubmissionListNavigator.vue, frontend/src/components/housing/submission/SubmissionsNavigator.vue
[PADS-249](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-249)
AssignedTo sorting fixed for submissions
Now full name is assigned for each submission in SubmissionsNavigator and passed to SubmissionListNavigator
user.fullName is directly fed to DataTable column
=> Fix AssignedTo Sorting

frontend/src/components/form/StepperNavigation.vue
added scroll to top functionality when clicking prev and next buttons on NavigationStepper component
Better work flow and saves confusion when navigating between tabs
[PADS-267](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-267)
=> Page scrolls to top on next and previous

frontend/src/components/housing/enquiry/EnquiryIntakeConfirmation.vue, frontend/src/components/housing/enquiry/EnquiryIntakeForm.vue, frontend/src/components/housing/enquiry/EnquiryListProponent.vue, frontend/src/components/housing/submission/IntakeAssistanceConfirmation.vue, frontend/src/components/housing/submission/SubmissionIntakeConfirmation.vue, frontend/src/components/housing/submission/SubmissionIntakeForm.vue, frontend/src/components/housing/submission/SubmissionListProponent.vue, frontend/src/components/layout/Navbar.vue, frontend/src/services/permissionService.ts, frontend/src/views/HomeView.vue, frontend/src/views/housing/HousingView.vue, frontend/src/views/housing/SubmissionsView.vue
[PADS-279](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-279)
Text updates, refer the ticket for exhaustive list
=> UI Text Updates

app/src/db/migrations/20240828000000_008-user-id-constraint.ts
Previous migration did not remove users correctly. Migration updated to correctly allow instances where there is more than 1 duplicate entry.
=> Update migration to better remove duplicate users

frontend/src/components/housing/submission/SubmissionIntakeForm.vue
When attempting to submit if there are validation errors, it will switch to the correct tab then scroll to the element with the error. 
=> Implement scroll to validation error element

charts/pcns/templates/secret.yaml
=> Remove bad label in helm secrets

charts/pcns/Chart.yaml, charts/pcns/README.md, charts/pcns/templates/secret.yaml
=> Add random default for object storage secret

app/src/db/seeds/prod_groups.ts, app/src/db/seeds/test_groups.ts
=> Update database user group seeds

app/src/controllers/submission.ts
The unique constraint on activity is being triggered somehow
=> Attempting to resolve issue import CHEFS data

frontend/src/components/housing/enquiry/EnquiryIntakeForm.vue, frontend/src/components/housing/submission/SubmissionIntakeForm.vue, frontend/tests/unit/components/shasIntake/EnquiryIntakeForm.spec.ts
No longer prematurely trigger validation when loading draft enquiries or submission intakes.
Adjust enquiry tests to match
[PADS-281](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-281?)
=> Disable initial validation on loading drafts, fix heading error highlights

app/src/validators/user.ts, frontend/src/components/housing/enquiry/EnquiryForm.vue, frontend/src/components/housing/submission/SubmissionForm.vue, frontend/src/components/housing/submission/SubmissionListNavigator.vue, frontend/src/components/housing/submission/SubmissionStatistics.vue
Hotfix for searchUsers to exclude sub
Update validator
=> Hotfix for searchUsers to exclude sub, update validator

frontend/src/store/authzStore.ts
Adjusts the navigation permissions:
- Remove intake forms from non proponents
- Add status tracker to non proponents for testing
=> Remove intake form from non proponents. Add status tracker for testing

frontend/src/components/housing/submission/SubmissionListNavigator.vue
=> Fixed assignedTo Sorting

app/src/services/enquiry.ts, app/src/services/submission.ts
Resolves an issue with the soft delete of submissions and enquiries.
=> Resolve issue soft deleting submissions and enquiries

.vscode/extensions.json, frontend/src/store/authzStore.ts
- Enable user management navigation
- Adjust recommended VSCode extensions
=> Misc updates before deployment to test

frontend/src/components/form/internal/InputMaskInternal.vue, frontend/src/components/layout/Navbar.vue, frontend/src/router/index.ts, frontend/src/store/authzStore.ts
Housing enquiry permission added to admin, supervisor, navigator & navigator read-only
InputMaskInternal placeholder prop type changed to fix console warning
navbar permission updated for enquiry
=> Navigate housing enquiry

frontend/src/utils/constants/application.ts, frontend/src/views/user/UserManagementView.vue
Changed user search to only include users that don't have the developer group.
Developer users should only be handled in the back end
[PADS-308](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-308)
=> Remove Developer Users from UserTable

frontend/src/components/file/DocumentCard.vue, frontend/src/components/housing/enquiry/EnquiryListNavigator.vue, frontend/src/components/housing/submission/SubmissionForm.vue, frontend/src/components/housing/submission/SubmissionListNavigator.vue, frontend/src/components/note/NoteCard.vue, frontend/src/components/permit/PermitCard.vue, frontend/src/components/roadmap/Roadmap.vue, frontend/src/store/authzStore.ts, frontend/src/views/housing/enquiry/EnquiryView.vue, frontend/src/views/housing/submission/SubmissionView.vue
This PR disabled form fields and buttons on the Navigator views if the user does not have the correct permissions.
https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-315
=> Permissions checks for Navigator forms/buttons

app/src/routes/v1/enquiry.ts, app/src/routes/v1/submission.ts, app/src/validators/basic.ts, app/src/validators/enquiry.ts, app/src/validators/housing.ts, app/src/validators/submission.ts, app/tests/unit/validators/basic.spec.ts, frontend/src/components/housing/enquiry/EnquiryIntakeForm.vue
Resolves issue with incorrect validation on Submission create
Resolves issue with Enquiry auto save incorrectly calling a validation layer
=> Intake validation fixes

frontend/src/components/common/StatusPill.vue, frontend/src/components/permit/PermitCard.vue
[PADS-21](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-21) 
New StatusPill component
Permit card CSS updates
=> Permit Card Updates

frontend/src/components/file/DocumentCard.vue, frontend/src/components/housing/enquiry/EnquiryForm.vue, frontend/src/components/housing/submission/SubmissionForm.vue, frontend/src/components/housing/submission/SubmissionListNavigator.vue, frontend/src/components/housing/submission/SubmissionsNavigator.vue, frontend/src/components/note/NoteCard.vue, frontend/src/components/permit/PermitCard.vue, frontend/src/types/Enquiry.ts, frontend/src/types/Submission.ts, frontend/src/views/housing/enquiry/EnquiryView.vue, frontend/src/views/housing/submission/SubmissionView.vue
[PADS-333](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-333)
Added isCompleted check to EnquiryView
Added isCompleted check and re-open button to EnquiryForm
=> Close/Re-open Enquiry

frontend/src/components/file/DocumentCard.vue, frontend/src/components/housing/submission/SubmissionForm.vue, frontend/src/components/housing/submission/SubmissionListNavigator.vue, frontend/src/components/housing/submission/SubmissionsNavigator.vue, frontend/src/components/note/NoteCard.vue, frontend/src/components/permit/PermitCard.vue, frontend/src/types/Enquiry.ts, frontend/src/types/Submission.ts, frontend/src/views/housing/submission/SubmissionView.vue
[PADS-28](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-28)
[PADS-23](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-23)
InputSwitch added to SubmissionsNavigator to switch between closed/open Submissions/Enquiries
DocumentCard, NoteCard, PermitCard updated with editable/disabled
SubmissionForm updated with re-open a submission feature
SubmissionListNavigator updated - added Submission Type column to the datatable
SubmissionView updated - updates to editable/disabled prop for components
EnquiryStatus added to enums
=> Close/Re-open Activity

frontend/src/components/file/FileUpload.vue, frontend/src/components/housing/submission/SubmissionForm.vue, frontend/src/components/housing/submission/SubmissionsNavigator.vue, frontend/src/types/Document.ts, frontend/src/views/housing/SubmissionsView.vue, frontend/src/views/housing/submission/SubmissionView.vue
[PADS-269](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-269)
Added extension to Document frontend type
Completed submissions toggle design changes
=> Show file extension

frontend/src/assets/variables.scss, frontend/src/components/common/StatusPill.vue, frontend/src/components/permit/PermitCard.vue, frontend/src/components/permit/PermitModal.vue, frontend/src/utils/enums/housing.ts, frontend/tests/unit/components/permit/PermitCard.spec.ts
Update the status pill component to new design.
[PADS-377](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-377)
=> Update status pill component to new design

app/src/db/migrations/20241209000000_16-permit-complete-status.ts, app/src/utils/enums/housing.ts, frontend/src/components/permit/PermitStatusDescriptionModal.vue, frontend/src/utils/enums/housing.ts
Changed descriptions in Modal and Enums. Made migration file for status Granted -> Approved
As per business side
[PAD-394](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-394)
=> Updates to permit descriptions and issued status

charts/pcns/Chart.yaml, charts/pcns/README.md
=> Bump helm chart version

.github/workflows/on-push.yaml
Add oc install to test and prod pipelines
=> Add oc install to test and prod pipelines

frontend/src/components/housing/enquiry/EnquiryIntakeConfirmation.vue, frontend/src/components/housing/enquiry/EnquiryIntakeForm.vue, frontend/src/components/housing/enquiry/EnquiryListNavigator.vue, frontend/src/components/housing/enquiry/EnquiryListProponent.vue, frontend/src/components/housing/submission/SubmissionForm.vue, frontend/src/components/housing/submission/SubmissionListNavigator.vue, frontend/src/locales/en-CA.json, frontend/src/utils/templates.ts, frontend/src/views/housing/enquiry/EnquiryConfirmationView.vue, frontend/src/views/housing/project/ProjectView.vue, frontend/src/views/housing/submission/SubmissionConfirmationView.vue
[PADS-404](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-404)
Wording changes:
Intake confirmation pages updated
Intake forms updated
Navigator project/enquiry list views updated
en-CA updated
Email templates updated
=> FE Wording Changes

frontend/src/components/housing/submission/SubmissionIntakeForm.vue, frontend/src/components/housing/submission/SubmissionIntakeSchema.ts
Resolve assistance tab disappearing
=> Resolve assistance tab disappearing

SECURITY.md, app/package-lock.json, app/package.json, charts/pcns/Chart.yaml, charts/pcns/README.md, frontend/package-lock.json, frontend/package.json
Formally release PCNS v0.5
Documentation (non-breaking change with enhancements to documentation)
=> Release v0.5

app/src/controllers/enquiry.ts, frontend/src/assets/variables.scss, frontend/src/locales/en-CA.json, frontend/src/views/housing/project/ProjectView.vue, frontend/tests/unit/views/housing/project/ProjectView.spec.ts
[PADS-379](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-379)
ProjectView, en-CA & test updated
Related Enquiries table added to ProjectView
=> Proponent project view updates

frontend/src/components/permit/NotesModal.vue, frontend/src/components/permit/PermitCard.vue
Made layout changes to cards as per ticket
also added most recent update to card and new link to updates
[PADS-368](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-368)
=> Made changes to permit tab and permit cards

app/src/controllers/submission.ts, app/src/docs/v1.api-spec.yaml, app/src/services/submission.ts, app/src/validators/submission.ts, frontend/src/components/housing/submission/SubmissionsNavigator.vue, frontend/src/views/housing/HousingView.vue, frontend/tests/unit/service/submissionService.spec.ts, frontend/tests/unit/views/housing/HousingView.spec.ts
Changed getSubmissions in Housing View to searchSubmissions with the includedDeleted flag.
So that proponents aren't seeing any deleted submissions/projects.
[PADS-427](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-427)
Documentation (non-breaking change with enhancements to documentation)
=> Filter deleted projects from the My Projects list

frontend/src/locales/en-CA.json, frontend/src/views/housing/HousingView.vue, frontend/src/views/housing/project/ProjectView.vue, frontend/src/views/housing/submission/SubmissionView.vue, frontend/src/views/permit/PermitStatusView.vue, frontend/tests/unit/views/housing/submission/SubmissionView.spec.ts, frontend/tests/unit/views/permit/PermitStatusView.spec.ts
Added see proponents view button to nav submission view page
So that navs can help proponents with the tracker if they don't understand what they're seeing
=> Added see proponents view button to nav submission view page

frontend/src/components/user/UserCreateModal.vue, frontend/src/router/index.ts
Frontend dropdown sends proper user management role in request object
Adjust vue router to no longer scroll to top when navigating to the same route
[PADS-438](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-438)
=> Fix user management function, remove scroll to top on submission intake autosave

app/src/services/user.ts
Resolves major issue where new users were not being added to the user table.
Decouples the contact service calls from the main user transation.
=> Decouple contact from main user transaction

app/src/services/contact.ts, frontend/src/components/housing/submission/SubmissionForm.vue, frontend/src/components/housing/submission/SubmissionIntakeForm.vue
PADS 434: https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-434
FE: reformatted submission assistance object structure to account for new contact feature, disabled certain input fields for navigator submission 
BE: fix navigator submission form update by updating upsert contacts to properly handle upserting `activity_contact` entries 
=> Fix submission assist, navigator submission intake

.github/environments/values.prod.yaml, frontend/src/components/housing/CollectionDisclaimer.vue, frontend/src/locales/en-CA.json, frontend/src/utils/constants/housing.ts
[PADS-441](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-441)
Navigator email updated in collection disclaimer and prod config
=> Navigator Email Updated

app/src/services/contact.ts, frontend/src/components/housing/submission/SubmissionIntakeForm.vue
Upsert was functioning incorrectly for new users after the uuid generation was moved to the controller layer. This uses a proper upsert instead of branched create/update logic.
Resolve issue where intake drafts would return empty string for last name passing FE validation but failing BE. 
=> Resolve bug upserting contact data

frontend/src/assets/main.scss, frontend/src/components/common/Tooltip.vue, frontend/src/components/housing/enquiry/EnquiryIntakeForm.vue, frontend/src/components/housing/enquiry/EnquiryListProponent.vue, frontend/src/components/housing/submission/SubmissionDraftListProponent.vue, frontend/src/components/housing/submission/SubmissionIntakeForm.vue, frontend/src/views/housing/HousingView.vue
Certain tooltips, when the component they are attached to are clicked, with stay stuck displayed on screen instead of disappearing after mouse leaves the attached component.
Created a custom component wrapping divs with tooltip directives to fix this issue.
[PADS-428](https://github.com/bcgov/nr-permitconnect-navigator-service/pull/254)
=> Fix tooltip stuck being displayed.

frontend/src/components/common/StatusPill.vue
Fixed tooltip on status pill from being stuck when clicked.
=> Fix stuck tooltip on status pill

frontend/src/components/housing/submission/IntakeAssistanceConfirmation.vue, frontend/src/locales/en-CA.json, frontend/src/views/housing/HousingView.vue, frontend/src/views/housing/enquiry/EnquiryConfirmationView.vue, frontend/src/views/housing/submission/SubmissionView.vue, frontend/tests/unit/components/housing/submission/IntakeAssistanceConfirmation.spec.ts
Updated padding and spacing on several FE components.
Update IntakeAssistanceConfirmation with i18n work
[PADS-444](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-444)
=> Proponent styling changes, IntakeAssistanceConfirmation i18n work

app/app.ts, app/src/routes/v1/docs.ts
Update CSP 
Add nonce's when using self directives
=> Add nonce's when using self directives

app/src/db/migrations/20250211000000_024-update-permit-types.ts
Added additional data via DB migration to permit types of "Transportation and Transit" of the "agency" column .
Data inserted into the "permit_type" table.
Data is as follows: 
branch: 'Planning and Major Projects',
division: 'Highways and Regional Services',
source_system: 'Electronic Development Approvals System',
source_system_acronym: 'eDAS'
[PADS-455](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-455)
Breaking change (fix or feature that would cause existing functionality to change)
=> Migration to update Transportation Permit Types

frontend/src/components/housing/enquiry/EnquiryForm.vue, frontend/tests/unit/components/housing/enquiry/EnquiryForm.spec.ts
Added more EnquiryForm unit tests.
Some tests with onMounted, props, and UI tests
[PADS-415](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-415)
=> Added more EnquiryForm unit tests

frontend/src/components/file/DeleteDocument.vue, frontend/src/components/file/DocumentCard.vue, frontend/src/components/file/DocumentCardLite.vue
Prevent tooltip for the delete button getting stuck after clicking the delete button.
[PADS-457](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-457)
=> Fix stuck tooltip for delete button

SECURITY.md, app/package-lock.json, app/package.json, charts/pcns/Chart.yaml, charts/pcns/README.md, frontend/package-lock.json, frontend/package.json
Formally release v0.6.0
Bug fix (non-breaking change which fixes an issue) 
Documentation (non-breaking change with enhancements to documentation)
=> Release v0.6.0

frontend/src/components/permit/PermitModal.vue
Fix PermitModal to update SubmissionStore with permit note information instead of omitting it.
[PADS-445](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-445)
=> Update PermitModal to properly update submissionStore for permits

app/src/services/reporting.ts
Added Submission Type, Intake state, and Project state columns to data export query.
[PADS-459](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-459)
=> Add more columns to export data

.github/CODEOWNERS, app/src/db/seeds/dev_groups.ts
Update codeowners and dev db seed
=> Update codeowners and dev db seed

frontend/src/components/housing/submission/SubmissionIntakeForm.vue
Fix intake routing issue
- In a submitted form, clicking a stepper header would incorrectly route to a different url
Fix map GeoJSON reloading issue
- Data was incorrectly being set to null on form open
https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-467
=> Intake bug fixes

app/src/controllers/contact.ts, app/src/db/models/activty_contact.ts, app/src/db/models/contact.ts, app/src/docs/v1.api-spec.yaml, app/src/routes/v1/contact.ts, app/src/services/contact.ts, app/src/types/ActivityContact.ts, app/src/types/Contact.ts, app/src/types/index.ts, app/src/validators/contact.ts, app/tests/unit/controllers/contact.spec.ts, frontend/src/components/contact/ContactHistoryList.vue, frontend/src/components/contact/ContactsProponentsList.vue, frontend/src/components/housing/enquiry/EnquiryListNavigator.vue, frontend/src/components/housing/enquiry/EnquiryListProponent.vue, frontend/src/components/housing/projects/ProjectsList.vue, frontend/src/components/housing/submission/SubmissionBringForwardCalendar.vue, frontend/src/components/housing/submission/SubmissionDraftListProponent.vue, frontend/src/components/housing/submission/SubmissionListNavigator.vue, frontend/src/components/user/ATSUserLinkModal.vue, frontend/src/components/user/UserCreateModal.vue, frontend/src/components/user/UserTable.vue, frontend/src/services/contactService.ts, frontend/src/types/ActivityContact.ts, frontend/src/types/index.ts, frontend/src/views/internal/contact/ContactPageView.vue, frontend/src/views/internal/housing/project/ProjectView.vue, frontend/tests/unit/views/internal/contact/ContactPageView.spec.ts
Fixed incorrect enquiry and submission search for contact history so that contacts with no user attachment have correct history and so that any nav created submissions are still connected to the correct contact.
=> Fixed incorrect enquiry and submission search for contact history

frontend/src/ThemeOverride.ts, frontend/src/assets/main.scss, frontend/src/components/form/common/ContactCard.vue, frontend/src/components/form/common/LocationCard.vue, frontend/src/components/form/common/NaturalDisasterCard.vue, frontend/src/components/housing/CollectionDisclaimer.vue, frontend/src/components/housing/enquiry/EnquiryCard.vue, frontend/src/components/housing/enquiry/EnquiryIntakeForm.vue, frontend/src/components/housing/submission/SubmissionIntakeForm.vue, frontend/src/components/housing/submission/SubmissionsNavigator.vue, frontend/src/components/note/NoteCard.vue, frontend/src/components/permit/PermitCard.vue, frontend/src/locales/en-CA.json, frontend/src/views/external/housing/permit/PermitStatusView.vue, frontend/tests/unit/components/form/common/ContactCard.spec.ts, frontend/tests/unit/components/form/common/LocationCard.spec.ts, frontend/tests/unit/components/form/common/NaturalDisasterCard.spec.ts
- Certain information will be reused in other intake forms. Created reusable form components for Contact information, Location information, and Natural Disaster question.
- Removed a bunch of duplicate css for `p-card` so they should all share the same theme values now.
- Fixed a bug for the bring forward accordion not saving state.
=> Create some common form components

app/src/controllers/enquiry.ts, app/src/db/migrations/20250313000000_027-enquiry-form-updates.ts, app/src/db/models/enquiry.ts, app/src/db/prisma/schema.prisma, app/src/types/Enquiry.ts, app/src/utils/constants/housing.ts, app/src/utils/enums/housing.ts, app/src/validators/enquiry.ts, app/tests/unit/controllers/enquiry.spec.ts, frontend/src/components/housing/enquiry/EnquiryForm.vue, frontend/src/components/housing/enquiry/EnquiryListNavigator.vue, frontend/src/locales/en-CA.json, frontend/src/types/Enquiry.ts, frontend/src/utils/constants/housing.ts, frontend/src/utils/enums/application.ts, frontend/src/utils/enums/housing.ts, frontend/tests/unit/components/contact/ContactHistoryList.spec.ts, frontend/tests/unit/components/housing/enquiry/EnquiryCard.spec.ts, frontend/tests/unit/components/housing/enquiry/EnquiryForm.spec.ts, frontend/tests/unit/components/housing/enquiry/EnquiryListNavigator.spec.ts, frontend/tests/unit/components/housing/enquiry/EnquiryListProponent.spec.ts, frontend/tests/unit/components/housing/submission/SubmissionsNavigator.spec.ts, frontend/tests/unit/components/user/ATSUserCreateModal.spec.ts
[PADS-365](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-365)
Navigators can now create enquiries on behalf of proponents
New field added to the enquiry form
Enquiry create and update apis updated to allow empty enquiry and contact saves
Migration added to add new column
Validators updated
Tests updated
=> Navigator create enquiry & Enquiry form updates

app/src/controllers/enquiry.ts, app/src/db/migrations/20250313000000_027-enquiry-form-updates.ts, app/src/db/models/enquiry.ts, app/src/db/prisma/schema.prisma, app/src/types/Enquiry.ts, app/src/utils/constants/housing.ts, app/src/utils/enums/housing.ts, app/src/validators/enquiry.ts, app/tests/unit/controllers/enquiry.spec.ts, frontend/src/components/housing/enquiry/EnquiryForm.vue, frontend/src/components/housing/enquiry/EnquiryListNavigator.vue, frontend/src/locales/en-CA.json, frontend/src/types/Enquiry.ts, frontend/src/utils/constants/housing.ts, frontend/src/utils/enums/application.ts, frontend/src/utils/enums/housing.ts, frontend/tests/unit/components/common/Breadcrumb.spec.ts, frontend/tests/unit/components/contact/ContactHistoryList.spec.ts, frontend/tests/unit/components/housing/enquiry/EnquiryCard.spec.ts, frontend/tests/unit/components/housing/enquiry/EnquiryForm.spec.ts, frontend/tests/unit/components/housing/enquiry/EnquiryListNavigator.spec.ts, frontend/tests/unit/components/housing/enquiry/EnquiryListProponent.spec.ts, frontend/tests/unit/components/housing/submission/SubmissionsNavigator.spec.ts, frontend/tests/unit/components/user/ATSUserCreateModal.spec.ts
Navigator create enquiry, enquiry form updates, apis updated, migratioon to add new column
=> Navigator create enquiry

app/src/controllers/permit.ts, app/src/db/migrations/20250320000000_028-electrification.ts, app/src/db/prisma/schema.prisma, app/src/routes/v1/permit.ts, app/src/services/permit.ts, app/tests/unit/controllers/permit.spec.ts, frontend/src/services/permitService.ts, frontend/src/utils/enums/application.ts, frontend/src/views/external/housing/project/ProjectIntakeView.vue, frontend/src/views/external/housing/project/ProjectView.vue, frontend/src/views/internal/housing/project/ProjectView.vue, frontend/tests/unit/service/permitService.spec.ts
Add electrification permit types to `permit_type` table.
Add `permit_type_initiative_xref` table and populate.
Update `getPermitTypes()` to now require and initiative to select permits for.
https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-476
=> Add electrification permit types

frontend/src/views/internal/housing/project/ProjectView.vue
Missing button when no permits on project has been fixed
so that navs can add permits to projects that contain no permits
[PADS-509](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-509)
=> Fix missing add permit button in internal ProjectView

frontend/src/components/housing/enquiry/EnquiryListProponent.vue
[PADS-511](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-511) 
Removed hyperlink for related enquiries in proponent view created by navs
=> Removed hyperlink for related enquiries

frontend/src/router/index.ts, frontend/src/store/enquiryStore.ts, frontend/src/store/permitStore.ts, frontend/src/store/submissionStore.ts, frontend/src/utils/utils.ts
Resetting stores when view/route changes
so that incorrect data isn't carried across views/routes
[PAD-515](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-515)
=> Reset store on view/route changes

app/src/db/models/permit.ts, frontend/src/components/permit/NotesModal.vue, frontend/src/components/permit/PermitCard.vue, frontend/src/components/permit/PermitModal.vue, frontend/src/locales/en-CA.json, frontend/src/router/index.ts, frontend/src/services/index.ts, frontend/src/utils/templates.ts, frontend/src/views/external/housing/project/ProjectView.vue, frontend/tests/unit/components/permit/PermitCard.spec.ts, frontend/tests/unit/components/permit/PermitModal.spec.ts, frontend/tests/unit/components/permit/PermitNotesModal.spec.ts
Added emails going on out on Navs adding notes to a permit application.
[PADS-494](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-494)
=> Permit note notifications

.github/CODEOWNERS, .github/workflows/unit-tests.yaml
Update unit tests to use 22.x instead of 22.0.
Remove 18.x tests as Node 18 is EOL
Update codeowners file to point to github team
=> Use correct LTS version for unit tests. Update codeowners file

app/src/db/migrations/20250430000000_029-user-business-name.ts, app/src/db/models/contact.ts, app/src/db/models/user.ts, app/src/db/prisma/schema.prisma, app/src/services/contact.ts, app/src/services/user.ts, app/src/types/Contact.ts, app/src/types/User.ts, app/tests/unit/controllers/user.spec.ts, app/tests/unit/services/user.spec.ts, frontend/src/components/housing/submission/SubmissionIntakeForm.vue, frontend/src/locales/en-CA.json, frontend/src/types/Contact.ts
[PADS-450](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-450)
SubmissionIntakeForm updated to autofill bceidBusinessName
Migration added to add new column to the user table
User model updated
Contact search api updated to join user table and add BCeID business name to the contact table search result
Contact model updated to parse the new result
User service updated to grab bceidBusinessName from JWT token and update the user table on login
Contact, User types updated
Tests updated
=> Autofill Business Name on the Submission Intake Form

frontend/src/assets/images/H.Land.Button.svg, frontend/src/components/projectCommon/submission/SubmissionDraftListProponent.vue, frontend/src/components/roadmap/Roadmap.vue, frontend/src/locales/en-CA.json, frontend/src/router/externalElectrification.ts, frontend/src/utils/keys.ts, frontend/src/views/HomeView.vue, frontend/src/views/external/electrification/ElectrificationView.vue, frontend/src/views/internal/electrification/ElectrificationView.vue, frontend/src/views/internal/electrification/contact/ContactPageView.vue, frontend/src/views/internal/electrification/contact/ContactsView.vue, frontend/src/views/internal/housing/HousingView.vue, frontend/src/views/internal/housing/contact/ContactPageView.vue, frontend/src/views/internal/housing/contact/ContactsView.vue, frontend/tests/unit/components/housing/submission/SubmissionDraftListProponent.spec.ts, frontend/tests/unit/components/roadmap/Roadmap.spec.ts, frontend/tests/unit/views/external/electrification/ElectrificationView.spec.ts
Added new view for props electrification projects.
[PADS-496](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-496)
Note: Cannot click into projects until the Props project view is complete for electrification. This will just be for this view, doesn't contain any code from the other two electrification PRs.
=> My Projects View for Electrification

frontend/src/components/user/ATSUserCreateModal.vue
[PADS-553](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-553)
Ats Client Payload Updated
=> ATS Client Payload Updated

app/src/controllers/housingProject.ts, app/src/services/yars.ts, app/src/types/Group.ts, frontend/src/components/layout/AppLayout.vue, frontend/src/components/layout/DevelopmentRoleOverride.vue, frontend/src/router/index.ts, frontend/src/store/authzStore.ts, frontend/src/types/Group.ts, frontend/src/views/DeveloperView.vue
Frontend navigational mappings now take a users group initiative into account. Prior to this change, for example, a user with Housing/Admin group could access the Electrification user management panel (although no data would load). This fix prevents unintended navigational abilities.
https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-557
=> Update FE navigation mapping

app/src/controllers/electrificationProject.ts, frontend/src/components/electrification/project/ProjectIntakeForm.vue, frontend/src/components/electrification/project/ProjectIntakeSchema.ts, frontend/src/components/form/AutoComplete.vue, frontend/src/components/housing/submission/SubmissionIntakeForm.vue, frontend/src/components/housing/submission/SubmissionIntakeSchema.ts, frontend/tests/unit/components/shasIntake/SubmissionIntakeForm.spec.ts
Resolves the issue where selection an option in the AutoComplete drop down sometimes does not set it. 
This fix removes the `forceSelection` option from PrimeVue and does a custom validation in the `Yup` layer against the most recent search results.
Additionally fixes an issue found in the electrification intake draft saving.
https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-567
=> Fix AutoComplete validation issue

frontend/src/views/HomeView.vue
Electrification button added back for when it's time to move proponent electrification to prod
[PADS-542](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-542)
=> Added electrification button back for all users

app/app.ts, app/config/features-default.json, app/src/utils/utils.ts, app/state.ts, app/tests/unit/components/utils.spec.ts, frontend/src/store/featureStore.ts, frontend/src/store/index.ts
Add basic feature flag toggling. JSON file read in at app start. Key/values are passed via `/config` endpoint to front end. New feature store added. A computed getters should be added for feature flag pulling from the config store.
=> Add basic feature flag toggling

app/app.ts, app/bin/www.ts, app/package.json, app/src/db/utils/utils.ts, app/src/utils/cache/codes.ts, app/state.ts, app/tests/unit/db/utils.test.ts
Move & rewrite application startup and shutdown checks.
Add application health checks on startup.
=> Add application health checks

app/src/controllers/contact.ts, app/src/db/migrations/20250529000000_034-contact-updater.ts, app/src/db/models/contact.ts, app/src/docs/v1.api-spec.yaml, app/src/routes/v1/contact.ts, app/src/services/contact.ts, app/src/types/ContactSearchParameters.ts, app/src/validators/contact.ts, app/tests/unit/controllers/contact.spec.ts, frontend/src/components/contact/ContactForm.vue, frontend/src/components/contact/ContactPage.vue, frontend/src/components/contact/ContactsProponentsList.vue, frontend/src/components/contact/UpdateContactModal.vue, frontend/src/locales/en-CA.json, frontend/src/services/contactService.ts, frontend/src/types/Contact.ts, frontend/src/types/ContactSearchParameters.ts, frontend/src/views/contact/ContactView.vue, frontend/src/views/internal/electrification/contact/ContactPageView.vue, frontend/src/views/internal/electrification/contact/ContactsView.vue, frontend/src/views/internal/housing/contact/ContactPageView.vue, frontend/src/views/internal/housing/contact/ContactsView.vue, frontend/tests/unit/components/contact/ContactForm.spec.ts, frontend/tests/unit/components/contact/ContactPage.spec.ts, frontend/tests/unit/components/contact/ContactsProponentsList.spec.ts, frontend/tests/unit/components/contact/UpdateContactModal.spec.ts
Added delete contact API call.
Added new yars role, `CONTACT_UPDATER`, that allows proponents and read only navs to update their contact info without giving them the ability to delete contacts that comes from the `CONTACT_EDITOR` role.
Implemented new frontend flow and components to match [figma](https://www.figma.com/design/uW80J51g8OHm5fWICDdW9x/PAT--Latest-?node-id=7254-17104&t=b82gto5vvSOJxnSK-1) for Navs to update and delete contacts.
So that Navs can manage contacts safely away from the context of projects and enquiries.
[PADS-535](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-535)
=> Allow edit and delete on non-User Contacts via Contacts List

app/src/controllers/contact.ts, app/src/controllers/electrificationProject.ts, app/src/controllers/enquiry.ts, app/src/controllers/housingProject.ts, app/src/docs/v1.api-spec.yaml, app/src/routes/v1/contact.ts, app/src/services/activityContact.ts, app/src/services/contact.ts, app/src/services/index.ts, app/src/utils/utils.ts, app/src/validators/contact.ts, app/src/validators/electrificationProject.ts, app/src/validators/housingProject.ts, app/tests/unit/controllers/electrificationProject.spec.ts, app/tests/unit/controllers/enquiry.spec.ts, frontend/src/components/contact/ContactSearchModal.vue, frontend/src/components/electrification/project/ProjectForm.vue, frontend/src/components/form/common/ContactCardNavForm.vue, frontend/src/components/housing/submission/SubmissionForm.vue, frontend/src/components/projectCommon/enquiry/EnquiryForm.vue, frontend/src/locales/en-CA.json, frontend/src/services/contactService.ts
[PADS-491](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-491) 
Backend: 
electrificationProject, enquiry, housingProject controllers updated to prevent contact/activity_contact duplicates during an update
New activityContact service file for delete and upsert
ContactService updated with insertContacts'
Frontend:
New ContactSearchModal
Search and pick contact functionality added to ProjectForm, SubmissionForm, EnquiryForm and ContactCardNavForm
en-CA updated
Tests updated
=> Contact Selection in Nav Project/Enquiry Forms

app/src/services/user.ts, app/tests/unit/services/user.spec.ts
BCeID crams the entire name into `firstName`. 
This PR attempts to parse the first word in `firstName` into the first name and the rest into last name. If only a single word is present then the last name will default to a single whitespace character.
This does not name guarantee correctness, but a null last name breaks ATS. Users are able to correctly change their information whenever they want.
https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-607
=> Try to correct BCeID naming for initial contact

frontend/src/components/authorization/AuthorizationForm.vue
Added setEmptyStringsToNull sanitization function for form values on Authorization form.
Empty strings are able to be passed to db and causing errors with backend validator.
[PADS-625](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-625)
=> Added form sanitization to new Authorization form

app/src/services/reporting.ts, frontend/src/components/housing/submission/SubmissionIntakeSchema.ts
[PADS-631](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-631)
Query fixed for selecting prod data
=> Bugfix Download Prod Data

app/src/db/migrations/20250807000000_039-update-statistics-note-type.ts, frontend/src/components/common/Breadcrumb.vue, frontend/src/components/electrification/project/ProjectForm.vue, frontend/src/components/electrification/submission/SubmissionListNavigatorElectrification.vue, frontend/src/components/housing/submission/SubmissionForm.vue, frontend/src/components/housing/submission/SubmissionListNavigatorHousing.vue, frontend/src/components/housing/submission/SubmissionStatistics.vue, frontend/src/components/housing/submission/SubmissionsNavigator.vue, frontend/src/utils/constants/projectCommon.ts, frontend/src/utils/enums/projectCommon.ts, frontend/src/views/internal/electrification/authorization/AuthorizationView.vue, frontend/src/views/internal/housing/HousingView.vue, frontend/tests/unit/components/authorization/RequiredAuths.ts
[PADS-521](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-521)
Migration added to update enquiry note_type to General & statistic function
Updates to SubmissionsNavigator view
Basic info validation
=> Navigator Usability Improvements

frontend/src/components/authorization/AuthorizationCard.vue, frontend/src/components/authorization/AuthorizationCardIntake.vue, frontend/src/components/authorization/AuthorizationCardLite.vue, frontend/src/components/authorization/AuthorizationForm.vue, frontend/src/components/authorization/AuthorizationStatusUpdatesCard.vue, frontend/src/locales/en-CA.json, frontend/src/store/projectStore.ts, frontend/src/views/internal/electrification/authorization/AuthorizationView.vue, frontend/src/views/internal/electrification/project/ProjectView.vue, frontend/src/views/internal/housing/authorization/AuthorizationView.vue, frontend/src/views/internal/housing/project/ProjectView.vue
[PADS-633](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-633)
=> Navigator Authorization Tab Usability Improvements

frontend/src/components/note/NoteBanner.vue, frontend/src/components/note/ShownToProponentModal.vue, frontend/src/locales/en-CA.json, frontend/src/store/projectStore.ts, frontend/src/types/NoteHistory.ts, frontend/src/views/external/electrification/project/ProjectView.vue, frontend/src/views/external/housing/project/ProjectView.vue, frontend/tests/unit/components/note/NoteBanner.spec.ts
[PADS-554](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-554) 
Notes now shown to proponent
=> Tracker Improvements Proponent Notes

app/src/validators/ats.ts
ATS notes field can accept up to 4000 characters.
https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-651
=> Bugfix: ATS notes field can accept up to 4000 characters
